### ISSUE TITLE
Document basic_consume, poor error reporting

### ISSUE THREAD

**Issue by xabufr** [sozu-proxy/lapin#206] opened 2019-09-03 08:26 UTC
Hi !

I've been faced to strange connection error.
After investigating I've found that using a queue declared by another channel as an argument to `basic_consume` produces a connection error (because not registered in channel's queues).
This behavior isn't documented, and I don't think it is a limitation of AMQP protocol (as it only needs a queue name).
Using a queue declared by the same channel solves the problem.
It's not bad, but it should at least be documented.

Moreover I found that it was particularly difficult to find the origin of this error.
I know you're doing a lot of refactoring, but when done it would be nice to have more traces and a better error reporting system, to know exactly what goes wrong.

**Comment by jonathanstrong** [comment] 2019-09-04 05:46
if I could chime in ...

one thing that was confusing to me as I implemented basic consume for the first time (converting what had been basic get calls), was the use of `Confirmation::as_error` vs. `wait` or `try_wait`. Originally I was looping on `Confirmation::try_wait` inside `ConsumerDelegate::on_new_delivery`. This did not work, and I was very confused until I noticed the example code used `as_error`. However, there was no documentation regarding 1) what `as_error` does, compared to `wait`, 2) why it's necessary inside `on_new_delivery` to use `as_error`. 

Thanks for your work on a great library, thought this would help illuminate what might be confusing for someone approaching the api fresh.

**Comment by Keruspe** [comment] 2019-09-04 10:20
@xabufr 
It actually is a limitation from AMQP. We used to only require the queue name, and we now require a Queue object to force users to declare it beforehand. But yeah, it has to be declared on the same channel, otherwise it's not accepted by the rabbitmq server. The error you're getting is the raw error from the rabbitmq server.

wrt the refactoring, it's basically done now, so yeah, improving errors would be nice now

**Comment by Keruspe** [comment] 2019-09-04 10:21
@jonathanstrong as_error/into_error is just confusing and shouldn't be used, i'll drop those. See #204 for this problem.

**Comment by Keruspe** [comment] 2020-02-25 17:09
Ok, the root cause of this error was just fixed in master, and will be part of 0.31.0 which will be released shortly.

Also, 0.29 and 0.30 added some much better reporting

**Closed** 2020-04-11 16:10 UTC
