### ISSUE TITLE
failed to handle frame: NotConnected

### ISSUE THREAD

**Issue by whitfin** [sozu-proxy/lapin#109] opened 2018-05-17 23:35 UTC
Hi! 

I'm using latest master, and I randomly see `failed to handle frame: NotConnected` before any messages are received using what is practically the futures example. I see absolutely nothing in the debug logs beyond this:

```
 INFO  my_project                > Starting consumer with id 2...
 DEBUG tokio_reactor             > loop process - 1 events, 0.000s
 DEBUG tokio_reactor             > loop process - 1 events, 0.000s
 DEBUG tokio_reactor             > loop process - 1 events, 0.000s
 DEBUG tokio_reactor             > loop process - 1 events, 0.000s
 INFO  my_project                > got consumer stream
 DEBUG tokio_reactor             > loop process - 1 events, 0.000s
 DEBUG tokio_reactor             > loop process - 1 events, 0.000s
thread 'tokio-runtime-worker-0' panicked at 'failed to handle frame: NotConnected', src/main.rs:114:36
note: Run with `RUST_BACKTRACE=1` for a backtrace.
 DEBUG tokio_reactor             > dropping I/O source: 0
 DEBUG tokio_reactor             > loop process - 1 events, 0.000s
 DEBUG tokio_reactor::background > shutting background reactor on idle
 DEBUG tokio_reactor::background > background reactor has shutdown
```

Any ideas what might be doing this? I used my client to create queues, etc, so it appears that the channels should work fine. Happy to debug as needed!

**Comment by whitfin** [comment] 2018-05-18 00:03
Also, FWIW, if I spawn multiple channels in a loop, this happens:

```
 INFO  my_project > Starting consumer with id 4...
 INFO  my_project > Starting consumer with id 2...
 INFO  my_project > Starting consumer with id 3...
 INFO  my_project > Starting consumer with id 7...
 INFO  my_project > got consumer stream
 INFO  my_project > got consumer stream
```

It skips channels `5`, `6` and `8`, and only connects the stream on two of them... Looks like a bug somewhere?

**Comment by whitfin** [comment] 2018-05-18 00:37
Further logs discovered during `trace`:

```
 TRACE lapin_futures::transport  > amqp decoder; frame=Method(8, Basic(Deliver(Deliver { consumer_tag: "amq.ctag-gqwDEqh4RreiB1Y2vspHUg", delivery_tag: 1, redelivered: false, exchange: "my_exchange", routing_key: "" })))
 TRACE lapin_futures::transport  > transport poll_recv; frame=Method(8, Basic(Deliver(Deliver { consumer_tag: "amq.ctag-gqwDEqh4RreiB1Y2vspHUg", delivery_tag: 1, redelivered: false, exchange: "my_exchange", routing_key: "" })))
 TRACE lapin_futures::transport  > amqp decoder; frame=Header(8, 60, ContentHeader { class_id: 60, weight: 0, body_size: 4, properties: Properties { content_type: None, content_encoding: None, headers: Some({}), delivery_mode: Some(1), priority: None, correlation_id: None, reply_to: None, expiration: None, message_id: None, timestamp: None, type_: None, user_id: None, app_id: None, cluster_id: None } })
 TRACE lapin_futures::transport  > transport poll_recv; frame=Header(8, 60, ContentHeader { class_id: 60, weight: 0, body_size: 4, properties: Properties { content_type: None, content_encoding: None, headers: Some({}), delivery_mode: Some(1), priority: None, correlation_id: None, reply_to: None, expiration: None, message_id: None, timestamp: None, type_: None, user_id: None, app_id: None, cluster_id: None } })
 TRACE lapin_futures::transport  > amqp decoder; frame=Body(8, [116, 101, 115, 116])
 TRACE lapin_futures::transport  > transport poll_recv; frame=Body(8, [116, 101, 115, 116])
 TRACE lapin_futures::transport  > transport poll_recv; status=NotReady
 TRACE lapin_futures::consumer   > poll transport; consumer_tag="" status=NotReady
 DEBUG tokio_reactor             > loop process - 1 events, 0.000s
 TRACE lapin_futures::consumer   > poll; consumer_tag=""
 TRACE lapin_futures::transport  > transport poll
 TRACE lapin_futures::transport  > amqp decoder; frame=Method(9, Basic(Deliver(Deliver { consumer_tag: "amq.ctag-Poz-ubjxYCv_VSSSRHbLUQ", delivery_tag: 2, redelivered: false, exchange: "my_exchange", routing_key: "" })))
 TRACE lapin_futures::transport  > transport poll_recv; frame=Method(9, Basic(Deliver(Deliver { consumer_tag: "amq.ctag-Poz-ubjxYCv_VSSSRHbLUQ", delivery_tag: 2, redelivered: false, exchange: "my_exchange", routing_key: "" })))
thread 'tokio-runtime-worker-2' panicked at 'failed to handle frame: NotConnected', src/main.rs:114:36
```

Regardless of it showing several messages, it appears that none of them get through to the `for_each`.

**Comment by whitfin** [comment] 2018-05-18 00:56
I've traced this back, and it appears that all consumers start correctly from this commit onwards: fd77946eacc2f5a0db9555c1cc4d47f421b6da67

However, I have been unable to backtrace far enough to a place where messages are actually received on the Tokio reform implementation.

**Comment by whitfin** [comment] 2018-05-18 01:16
This seems like it might be related to https://github.com/sozu-proxy/lapin/issues/65?

**Comment by kureuil** [comment] 2018-05-18 08:20
From the logs, I think the problem comes from the creation of the consumers. Could you try by setting an explicit consumer_tag on your consumers ? It would seem that lapin isn't using the consumer_tag returned by RabbitMQ when you send an empty one.

**Comment by Keruspe** [comment] 2018-05-18 12:52
After a quick look at the code, the consumer_tag returned by rabbitmq seems to be used

**Comment by Keruspe** [comment] 2018-05-18 12:56
Looks like you somehow use a channel before it's actually open

**Comment by Keruspe** [comment] 2018-05-18 13:18
Should be fixed by 1ade8f695e426adbd1a5456add4f86446cb52c80
Can you retry?

**Comment by whitfin** [comment] 2018-05-18 16:53
@Keruspe same issue; only a couple of the channels actually open, and even the ones which do never receive events.

**Comment by whitfin** [comment] 2018-05-18 17:05
```
#[macro_use] extern crate log;
extern crate lapin_futures as lapin;
extern crate futures;
extern crate tokio;
extern crate env_logger;

use futures::future::Future;
use futures::Stream;
use tokio::net::TcpStream;
use lapin::types::FieldTable;
use lapin::client::ConnectionOptions;
use lapin::channel::{BasicConsumeOptions,BasicGetOptions,BasicPublishOptions,BasicProperties,ConfirmSelectOptions,ExchangeBindOptions,ExchangeUnbindOptions,ExchangeDeclareOptions,ExchangeDeleteOptions,QueueBindOptions,QueueDeclareOptions};

fn main() {
  env_logger::init();

  let addr = "127.0.0.1:5672".parse().unwrap();

  tokio::run(
    TcpStream::connect(&addr).and_then(|stream| {
      lapin::client::Client::connect(stream, &ConnectionOptions {
        frame_max: 65535,
        ..Default::default()
      })
    }).and_then(|(client, heartbeat)| {
      tokio::spawn(heartbeat.map_err(|e| println!("{:?}", e)));

      client.create_confirm_channel(ConfirmSelectOptions::default()).and_then(|channel| {
        let id = channel.id;
        info!("created channel with id: {}", id);

        channel.queue_declare("hello", &QueueDeclareOptions::default(), &FieldTable::new()).and_then(move |_| {
          info!("channel {} declared queue {}", id, "hello");

          channel.exchange_declare("hello_exchange", "direct", &ExchangeDeclareOptions::default(), &FieldTable::new()).and_then(move |_| {
            channel.queue_bind("hello", "hello_exchange", "hello_2", &QueueBindOptions::default(), &FieldTable::new()).and_then(move |_| {
              channel.basic_publish(
                "hello_exchange",
                "hello_2",
                b"hello from tokio",
                &BasicPublishOptions::default(),
                BasicProperties::default().with_user_id("guest".to_string()).with_reply_to("foobar".to_string())
              ).map(|confirmation| {
                info!("publish got confirmation: {:?}", confirmation)
              }).and_then(move |_| {
                channel.exchange_bind("hello_exchange", "amq.direct", "test_bind", &ExchangeBindOptions::default(), &FieldTable::new()).and_then(move |_| {
                    channel.exchange_unbind("hello_exchange", "amq.direct", "test_bind", &ExchangeUnbindOptions::default(), &FieldTable::new()).and_then(move |_| {
                        channel.exchange_delete("hello_exchange", &ExchangeDeleteOptions::default()).and_then(move |_| {
                            channel.close(200, "Bye")
                        })
                    })
                })
              })
            })
          })
        })
      }).and_then(move |_| {
        client.create_channel()
      }).and_then(|channel| {
        let id = channel.id;
        info!("created channel with id: {}", id);

        let c = channel.clone();
        channel.queue_declare("hello", &QueueDeclareOptions::default(), &FieldTable::new()).and_then(move |_| {
          info!("channel {} declared queue {}", id, "hello");

          let ch = channel.clone();
          ch.basic_consume("hello", "my_consumer", &BasicConsumeOptions::default(), &FieldTable::new())
        }).and_then(|stream| {
          info!("got consumer stream");

          stream.for_each(move |message| {
            debug!("got message: {:?}", message);
            info!("decoded message: {:?}", std::str::from_utf8(&message.data).unwrap());
            c.basic_ack(message.delivery_tag)
          })
        })
      })
    }).map_err(|_| ())
  )
}
```

Here's a modified sample I'm working from. If you check the logs, the consumer never actually starts (you never see `"got consumer stream"` in the logs), and the message is never actually received. It appears to basically do nothing.

**Comment by whitfin** [comment] 2018-05-18 21:06
@Keruspe which version of RabbitMQ are you using? I wonder if it's version specific. Can you maybe push the exact code somewhere that you did this with so I can compare?

**Comment by Keruspe** [comment] 2018-05-18 21:12
Rabbitmq 3.7.5
I copy-pasted your example as examples/bug.rs and ran it with `cargo run
—example=bug` without editing anything.

**Comment by whitfin** [comment] 2018-05-18 21:39
@Keruspe think I might have figured it out (kinda). If I use an OOTB RabbitMQ, it looks fine. On my instance it sticks here:

```
DEBUG 2018-05-18T21:36:46Z: tokio_reactor::background: starting background reactor
DEBUG 2018-05-18T21:36:46Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2018-05-18T21:36:46Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2018-05-18T21:36:46Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2018-05-18T21:36:46Z: lapin_async::connection: client sending Connection::StartOk: Connection(StartOk(StartOk { client_properties: {"product": LongString("lapin")}, mechanism: "PLAIN", response: "\u{0}my_user\u{0}my_pass", locale: "en_US" }))
DEBUG 2018-05-18T21:36:46Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2018-05-18T21:36:46Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2018-05-18T21:36:46Z: lapin_async::connection: Server sent Connection::Tune: Tune { channel_max: 2047, frame_max: 131072, heartbeat: 60 }
DEBUG 2018-05-18T21:36:46Z: lapin_async::connection: client sending Connection::TuneOk: Connection(TuneOk(TuneOk { channel_max: 2047, frame_max: 65535, heartbeat: 60 }))
DEBUG 2018-05-18T21:36:46Z: lapin_async::connection: client sending Connection::Open: Connection(Open(Open { virtual_host: "chimera", capabilities: "", insist: false }))
DEBUG 2018-05-18T21:36:46Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2018-05-18T21:36:46Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2018-05-18T21:36:46Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2018-05-18T21:36:46Z: lapin_async::connection: Server sent Connection::OpenOk: OpenOk { known_hosts: "" }, client now connected
DEBUG 2018-05-18T21:36:46Z: lapin_futures::client: got client service
DEBUG 2018-05-18T21:36:46Z: lapin_futures::client: heartbeat; interval=60
DEBUG 2018-05-18T21:36:46Z: lapin_futures::client: poll heartbeat
DEBUG 2018-05-18T21:36:46Z: lapin_futures::client: Sending heartbeat
DEBUG 2018-05-18T21:36:46Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2018-05-18T21:36:46Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2018-05-18T21:36:46Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2018-05-18T21:36:46Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2018-05-18T21:36:46Z: tokio_reactor: loop process - 1 events, 0.000s
 INFO 2018-05-18T21:36:46Z: client: created channel with id: 1
DEBUG 2018-05-18T21:36:46Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2018-05-18T21:36:46Z: tokio_reactor: loop process - 1 events, 0.000s
 INFO 2018-05-18T21:36:46Z: client: channel 1 declared queue hello
DEBUG 2018-05-18T21:36:46Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2018-05-18T21:36:46Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2018-05-18T21:36:46Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2018-05-18T21:36:46Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2018-05-18T21:36:46Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2018-05-18T21:36:46Z: tokio_reactor: loop process - 1 events, 0.000s
 INFO 2018-05-18T21:36:46Z: lapin_futures::channel: message with tag 1 still in unacked: {1}
DEBUG 2018-05-18T21:36:46Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2018-05-18T21:36:46Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2018-05-18T21:37:46Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2018-05-18T21:37:46Z: lapin_futures::client: poll heartbeat
DEBUG 2018-05-18T21:37:46Z: lapin_futures::client: Sending heartbeat
DEBUG 2018-05-18T21:37:46Z: tokio_reactor: loop process - 1 events, 0.000s
```

Different authentication credentials, if that matters.

**Comment by Keruspe** [comment] 2018-05-19 05:36
Aaaaaah, yeah, that’s totally expected by the amqp spec. We have #32 which
might be a solution to avoid this kind of troubles

**Comment by whitfin** [comment] 2018-05-19 07:28
@Keruspe ok cool, that makes sense.

In general though, it appears that spawning multiple listeners via `tokio::spawn` on multiple channels is unreliable. I have consistently fine behaviour with a couple of listeners, but as soon as I have a larger number (i.e. 8, the number of cores) only a couple start properly and the others appear to hang. I'm pretty sure there's a bug here, just haven't quite found where it is yet.

**Comment by Keruspe** [comment] 2018-05-19 18:01
I can reproduce this one and I have a failing example that I’ll push to the repo later

**Comment by whitfin** [comment] 2018-05-19 20:33
I can confirm that the consumers example shows the same behaviour for me:

```
will create consumer 1
will create consumer 2
will create consumer 3
will create consumer 4
will create consumer 5
will create consumer 6
will create consumer 7
will create consumer 8
creating consumer 4
creating consumer 1
got stream for consumer 4
got stream for consumer 1
will publish message 1 for consumer 1
creating consumer 8
creating consumer 2
creating consumer 5
got stream for consumer 8
got stream for consumer 2
```

And then it just hangs, nothing else happens - if I send messages through the queue for one of the streams that did work (e.g. consumer 2 above), nothing is received and everything just hangs.

**Comment by Keruspe** [comment] 2018-05-20 06:37
This seems to be another issue than the NotConnected one though, right?
Can I close this one and open a new one to track it down?

**Comment by whitfin** [comment] 2018-05-20 14:16
@Keruspe yes I think that makes sense!

**Closed** 2018-05-20 20:33 UTC
