### ISSUE TITLE
Publisher confirms delayed by up to a minute

### ISSUE THREAD

**Issue by jothan** [sozu-proxy/lapin#251] opened 2020-04-04 03:55 UTC
Hi, it's me again !

I am testing publishing "large" messages (5.7 MiB) to RabbitMQ with the latest lapin with publisher confirms.

With smaller messages, (500KiB), they are confirmed right away. A simple Python script publishing the same large message takes from 3.5 to 4 seconds which is expected given the bandwidth.

I have a packet dump and key log file that I can share with you. Wireshark seems to have trouble following the whole message content, though.

From what I can tell, the heartbeat seems to somehow flush the output buffer:
(just before the ack):
2020-04-03 23:39:41.705-0400 DEBUG lapin::connection: received heartbeat from server    
2020-04-03 23:39:42.023-0400  INFO app::rabbitmq: Send ok

Sometimes, especially near program start, publishing these large messages can take about "only" 9 seconds.

I will do everything needed to help you reproduce this.

Good night,
Jonathan

**Comment by jothan** [comment] 2020-04-04 04:07
I am using TLS with Rustls.

**Comment by Keruspe** [comment] 2020-04-04 06:40
Do you use the same frame size with lapin and pika?

**Comment by Keruspe** [comment] 2020-04-04 07:51
How many of these messages do you send (per sec, per min, per hour ?) and how long does it take to reach this 1min delay?
I assume it’s compiled in release mode?

**Comment by Keruspe** [comment] 2020-04-04 08:11
One last detail that could help :
If you get the time before calling basic_publish, then after awaiting the promise, then again after awaiting the PublisherConfirm, how much time does each step take?
I suspect that the first one is the one causing the latency?

**Comment by jothan** [comment] 2020-04-04 16:14
Lapin and pika both seem to be using the same max frame size of 131072 bytes.

I am sending messages manually one at a time. Usually, the first one is fast and the others are slow. Release and debug mode both show the same behavior. The CPU is idle during the pauses.

First message:
```
2020-04-04 12:09:15.676-0400  INFO themis::rabbitmq: Sending message
2020-04-04 12:09:18.346-0400  INFO themis::rabbitmq: First await after 2.663975
2020-04-04 12:09:19.096-0400  INFO themis::rabbitmq: Second await after 3.4144313
2020-04-04 12:09:19.097-0400  INFO themis::rabbitmq: Send ok
```

Second message:
```
2020-04-04 12:09:25.409-0400  INFO themis::rabbitmq: Sending message
2020-04-04 12:09:27.892-0400  INFO themis::rabbitmq: First await after 2.4772127
2020-04-04 12:09:38.969-0400 DEBUG lapin::connection: received heartbeat from server    
2020-04-04 12:10:08.971-0400 DEBUG lapin::connection: received heartbeat from server    
2020-04-04 12:10:38.972-0400 DEBUG lapin::connection: received heartbeat from server    
2020-04-04 12:10:39.279-0400  INFO themis::rabbitmq: Second await after 73.86438
```

From this, it seems that the send takes the normal amount of time, while waiting for the ack takes a long and variable delay.

**Comment by jothan** [comment] 2020-04-04 16:26
Interestingly enough, using wait_for_confirms after the send yields identical behavior.

**Comment by Keruspe** [comment] 2020-04-04 18:06
That is to be expected as the two are using a common broadcaster of the same underlying promise.

The good news is: it’s not a performance issue in the io loop.
The bad news is: the wip optimisation of the io loop I have won’t solve this.

Given you see this behaviour starting with the second message, I think I’ll be able to reproduce. If I don’t I’ll get back to you

**Comment by Keruspe** [comment] 2020-04-04 18:42
Ok, so, with a random payload of 6MiB, on a local rabbitmq, I indeed can reproduce it:

```
[...]
[2020-04-04T18:39:30Z INFO  foo] Took 6ms to publish msg 95
[2020-04-04T18:39:30Z INFO  foo] Took 8ms to get ack for msg 95
[2020-04-04T18:39:30Z INFO  foo] Took 13ms to publish msg 96
[2020-04-04T18:39:30Z INFO  foo] Took 20ms to get ack for msg 96
[2020-04-04T18:39:30Z INFO  foo] Took 7ms to publish msg 97
[2020-04-04T18:39:30Z INFO  foo] Took 10ms to get ack for msg 97
[2020-04-04T18:39:30Z INFO  foo] Took 8ms to publish msg 98
[2020-04-04T18:40:58Z INFO  foo] Took 88341ms to get ack for msg 98
[...]
```

**Comment by Keruspe** [comment] 2020-04-04 18:51
Ok, I'm 90% sure that pika is lying to you and either only tells you when data is done (like the first await here), or has some sort of timeout.

**Comment by Keruspe** [comment] 2020-04-04 19:02
Let me explain why:
I only turned INFO level on, and added some key warn logs inside of lapin to trace the relevant places, here are the logs of one of these hanging moments (in this try, msg 33 hanged, then no hang until I stopped at 150)

```
[2020-04-04T18:51:43Z WARN  lapin::io_loop] ======================================= POLL ================================================= <= Waiting for socket to be writable
[2020-04-04T18:51:43Z WARN  lapin::io_loop] ======================================= POLL DONE ============================================ <= Given how some internals of the io loop works, it takes several polls to finish sending the payload
[2020-04-04T18:51:43Z WARN  lapin::io_loop] ======================================= POLL ================================================= <= Waiting for socket to be writable
[2020-04-04T18:51:43Z WARN  lapin::io_loop] ======================================= POLL DONE ============================================ <= This is the last time we've polled for writing, we're now writing the last frame
[2020-04-04T18:51:43Z WARN  lapin::io_loop] ======================================= POLL ================================================= <= Waiting for input from the server
[2020-04-04T18:51:43Z INFO  foo] Took 18ms to publish msg 33      <= Meanwhile, we get the notification that last frame's sent
[2020-04-04T18:51:43Z WARN  lapin::io_loop] ======================================= POLL DONE ============================================ <= We called the waker to send our heartbeat
[2020-04-04T18:51:43Z WARN  lapin::io_loop] ======================================= POLL ================================================= <= Sent our heartbeat, waiting for input from the server
[2020-04-04T18:52:12Z WARN  lapin::io_loop] ======================================= POLL DONE ============================================ <= Socket is readable, we received a heartbeat from the server
[2020-04-04T18:52:12Z WARN  lapin::connection] ========================================================= FRAME Heartbeat(0) ========================================================================
[2020-04-04T18:52:12Z WARN  lapin::io_loop] ======================================= POLL ================================================= <= Waiting for input from the server
[2020-04-04T18:52:12Z WARN  lapin::io_loop] ======================================= POLL DONE ============================================ <= We called the waker to send our heartbeat
[2020-04-04T18:52:12Z WARN  lapin::io_loop] ======================================= POLL ================================================= <= Sent our heartbeat, waiting for input from the server
[2020-04-04T18:52:42Z WARN  lapin::io_loop] ======================================= POLL DONE ============================================ <= Socket is readable, we received a heartbeat from the server
[2020-04-04T18:52:42Z WARN  lapin::connection] ========================================================= FRAME Heartbeat(0) ========================================================================
[2020-04-04T18:52:42Z WARN  lapin::io_loop] ======================================= POLL ================================================= <= Waiting for input from the server
[2020-04-04T18:52:42Z WARN  lapin::io_loop] ======================================= POLL DONE ============================================ <= We called the waker to send our heartbeat
[2020-04-04T18:52:42Z WARN  lapin::io_loop] ======================================= POLL ================================================= <= Sent our heartbeat, waiting for input from the server
[2020-04-04T18:53:12Z WARN  lapin::io_loop] ======================================= POLL DONE ============================================ <= Socket is readable, we received a heartbeat from the server
[2020-04-04T18:53:12Z WARN  lapin::connection] ========================================================= FRAME Heartbeat(0) ========================================================================
[2020-04-04T18:53:12Z WARN  lapin::io_loop] ======================================= POLL ================================================= <= Waiting for input from the server
[2020-04-04T18:53:12Z WARN  lapin::io_loop] ======================================= POLL DONE ============================================ <= We called the waker to send our heartbeat
[2020-04-04T18:53:12Z WARN  lapin::io_loop] ======================================= POLL ================================================= <= Sent our heartbeat, waiting for input from the server
[2020-04-04T18:53:12Z WARN  lapin::io_loop] ======================================= POLL DONE ============================================ <= Socket is readable, we finally received the ack from the server
[2020-04-04T18:53:12Z WARN  lapin::connection] ========================================================= FRAME Method(1, Basic(Ack(Ack { delivery_tag: 33, multiple: false }))) ========================================================================
[2020-04-04T18:53:12Z WARN  lapin::io_loop] ======================================= POLL =================================================  <= Waiting for input from the server
[2020-04-04T18:53:12Z INFO  foo] Took 89025ms to get ack for msg 33    <= Meanwhile, we get the notification that we got the ack
```

**Comment by Keruspe** [comment] 2020-04-04 19:58
I cannot make the rabbitmq server tell me why this is happening, but it looks like some kind of rate limiting thing somehow?
After adding more logs, thus making it slower, the firts message to hit this was the 1452nd

I cannot reproduce with bunny either, so it's unlikely pika is lying, but I cannot make any sense of this

**Comment by Keruspe** [comment] 2020-04-04 20:09
AH! I think I got it

**Comment by Keruspe** [comment] 2020-04-04 21:12
On a related note, after re-re-re-reading the publisher-confirms docs, I noticed some things were not properly handled: #252 #253 #254 

I'm still not sure about #253, whether the Basic.Return is done only for mandatory/immediate like for Ack or if it's everything for Nack

**Comment by jothan** [comment] 2020-04-04 23:10
I confirm the latest lapin fixes this issue !

Thanks again,
Jonathan

**Comment by jothan** [comment] 2020-04-04 23:15
Gosh, I sent like 5 messages that went through without an unreasonable delay and then I had one take 30 seconds with the ack coming in suspiciously close to the heartbeat message.

```
2020-04-04 19:13:11.344-0400 DEBUG lapin::connection: received heartbeat from server    
2020-04-04 19:13:11.620-0400  INFO themis::rabbitmq: Send ok
```

**Comment by jothan** [comment] 2020-04-04 23:16
If it helps anything, the exact payload size is 5880513 bytes.

**Comment by Keruspe** [comment] 2020-04-05 06:37
Will retry with a remote server, that probably helps reproducing.

Anyways, while the fix at least improves things, it’s not the right one and I’ll open an issue for that later

**Comment by Keruspe** [comment] 2020-04-05 15:53
Testing with a remote server is currently difficult due to my local connection for the time being.

Could you send me trace logs of a sent message for which it happens using lapin 0.38.0?

**Comment by jothan** [comment] 2020-04-06 11:44
I have not managed to reproduce this issue with logging fully enabled. The issue is still there on the latest master.

**Comment by jothan** [comment] 2020-04-06 12:09
When I said "still there", I've only had one delayed message with the ack suspiciously close to the heartbeat this morning so far.

**Comment by Keruspe** [comment] 2020-04-06 12:14
So, correct me if I'm mistaken:

- the issue cannot be reproduced with full logging enabled (or is a lot harder to reproduce)
- depends on some "latency" or such given in > 2 million messages on a local rabbitmq I didn't hit it once
- only happens in release mode, once every now and then, close to an incoming heartbeat from the server

Does it seem that the Ack is being processed before or after the heartbeat?

**Comment by Keruspe** [comment] 2020-04-06 12:27
I've left a test running between two servers printing when we take more that 1s to send or more that 2s to get the ack, using rustls, with payload of 6 MiB.
Current rate is ~1.7 ack per sec which roughly makes 6k ack per hour.
I'll leave it running for the next 8 hours or so and we'll see how much of the ~48k messages will have hit this.

**Comment by jothan** [comment] 2020-04-06 13:13
I think you have summarized the situation very well. debug or release mode seems to have no effect.

In the one suspicous case, the heartbeat arrives before the ack is processed.

**Comment by Keruspe** [comment] 2020-04-06 16:10
Ok, this is way weirder than it seems, actually. I'm not sure if we're doing something wrong, or if the server is (probably us, but I don't see anything that could cause this):

I managed to reproduce it after 3h: msg 18926 took 42654ms to ack      

It was indeed with a Heartbeat message.

It wasn't *any* heartbeat message though. It was the second one sent by the server since connecting. The first one being after 30s as expected, and the second one after... 3 hours?
Given we log the heartbeat frame as soon as we get it, and the fact that we actually get acks, this means that we were able to read from the socket, but never actually received a heartbeat.

Not sure if we sent more. if we didn't that could maybe explain things? Not sure why we wouldn't, nor which other leads I could follow here.
Re-running with more logs

**Comment by Keruspe** [comment] 2020-04-06 16:33
Took a lot less time to reproduce now, I might retry with trace logs.

Here is what I gathered:
- it was not the second heartbeat, that's just some bug or feature in env_logger I guess?
- these logs (the first numer is the number of ms since program start):

```
73632 poll; can_read=false, can_write=true, has_data=false      <= Socket is not readable, is writable but we have nothing to write
120182 poll done; can_read=true, can_write=true, has_data=false <= Socket becomes readable 50s later
received heartbeat from server                                  
120182 poll; can_read=true, can_write=true, has_data=false      
120182 poll done; can_read=true, can_write=true, has_data=false 
120182 poll; can_read=false, can_write=true, has_data=false     <= Socket is no longer readable
120350 poll done; can_read=true, can_write=true, has_data=false   <= Socket is readable again
sent heartbeat to server                                        
Received ack 64                                                 
120350 poll; can_read=true, can_write=true, has_data=false      
120350 poll done; can_read=true, can_write=true, has_data=false 
120350 poll; can_read=false, can_write=true, has_data=false     
120617 msg 64 took 47394ms to ack     <= The message that took a long time to ack was just finished sending at the begining of these logs                          
```

**Comment by Keruspe** [comment] 2020-04-06 17:36
I have an idea but I’m not sure if it’ll change anything but will definitely make things cleaner wrt heartbeat sending

**Comment by jothan** [comment] 2020-04-06 21:05
Was the heartbeat send consuming a wakeup that was needed for writing the frame originally, stalling the send in the process ?

**Comment by Keruspe** [comment] 2020-04-06 21:35
Heh, I didn’t mean to close the issue.
I have some tests running still.
There was no such things but in some cases we would wait more than we should before sending heartbeat as we didn’t wake the loop and we were already waiting twice what we should have (which is a regression since at some point we definitely did the /2)
I don’t know if it’s going to have an influence on this but the server might consider us in a weird state if we don’t send the heartbeat when expected.
Given the ack comes alongside an heartbeat, that’s a theory worth exploring.
I still don’t understand why the logs of the sent heartbeat pop every 30s as expected while the logs for the received ones are basically missing for most of them.

**Comment by Keruspe** [comment] 2020-04-07 07:02
I'm approaching 80k sent messages and 0 ack took more that 2s. Can you try and see if you still can reproduce @jothan ?

It's still bothering me though, I see all the "send heartbeat" logs but only one "received heartbeat from server" at the beginning

**Comment by Keruspe** [comment] 2020-04-07 07:10
I guess this is why: `Any sent octet is a valid substitute for a heartbeat, thus heartbeats only have to be sent if nonon-heartbeat AMQP traffic is sent for longer than one heartbeat interval`

**Comment by Keruspe** [comment] 2020-04-07 07:11
Meaning that when we receive that "second heartbeat", it's indeed because the server sent nothing to us for some time

**Comment by Keruspe** [comment] 2020-04-07 10:13
Couldn't reproduce after 150k messages ack'ed.
Still not sure how the heartbeats hickups could have caused that, but I believe we're good now.
We're following the same rules as the server now, wrt when to send or not heartbeat, we were trying a little too hard before.

**Closed by Keruspe** 2020-04-07 10:13 UTC

**Comment by jothan** [comment] 2020-04-15 13:51
@Keruspe I'm still getting hit by this intermittently, it comes and goes, even with the lastest lapin master.

CloudAMQP offers free trials, it should be possible to reproduce this issue with their broker.
