### ISSUE TITLE
Unable to send payload ≥ 48KiB with TLS activated

### ISSUE THREAD

**Issue by hylobates-agilis** [sozu-proxy/lapin#233] opened 2020-02-22 18:53 UTC
Hi,

I’ve just ran into an issue where I cannot send a payload of more than 48KiB with lapin when using TLS.

I generated a 48KiB file with this command:
```
< /dev/urandom tr -dc A-Za-z0-9 | head -c $((48 * 1024)) > /tmp/youpi
```

With sample script (without SSL), message is delivered properly :

```
// std
use std::fs;

// lapin
use lapin::{
  BasicProperties, Connection, Channel, ConnectionProperties,
  options::*,
};

fn main() {
    let conn = Connection::connect("amqp://test:test@valid.fqdn/demo", ConnectionProperties::default()).wait().unwrap();

    let chan = conn.create_channel().wait().unwrap();

    let message = fs::read_to_string("/tmp/youpi").unwrap();

    chan.basic_publish("", "youpi", BasicPublishOptions::default(), message.as_bytes().to_vec(), BasicProperties::default().with_delivery_mode(2)).wait().unwrap();
}
```

If I just replaced with `amqps`, messages are not delivered. If you wrap `basic_publish` between `tx_select()` and `tx_commit()`, it hangs indefinitely on `tx_commit()` call. Delivery options does not seem to have any effect, it is just my current use case.

Wasn’t able to reproduce with python3-pika with the same file/same size with TLS activated, so I supposed the issue lied somewhere inside lapin (version used v0.28.4).

Sorry, I wasn’t able to produce more logs/traces (I don’t know how to do that to be honest).

**Comment by Keruspe** [comment] 2020-02-23 13:35
Could you retry by calling `env_logger::init()` before, and running with `RUST_LOG=trace`?

**Comment by hylobates-agilis** [comment] 2020-02-23 14:00
Sure thing, here you go.

[test_with_amqp.txt](https://github.com/sozu-proxy/lapin/files/4241342/test_with_amqp.txt)
[test_with_amqps.txt](https://github.com/sozu-proxy/lapin/files/4241343/test_with_amqps.txt)

If you need anything else (RabbitMQ version/OS, etc…), please just ask.

**Comment by Keruspe** [comment] 2020-02-23 14:12
If you explicitely close the channel after your publish, does it work?

**Comment by hylobates-agilis** [comment] 2020-02-23 14:29
Just added at the end:

```
chan.close(200, "OK").wait().unwrap();
```
AMQP: works fine.
AMQPS: hangs indefinetely (add to ^C it)

Bonus trace:

[close_channel_amqp.txt](https://github.com/sozu-proxy/lapin/files/4241405/close_channel_amqp.txt)
[close_channel_amqps.txt](https://github.com/sozu-proxy/lapin/files/4241406/close_channel_amqps.txt)

**Comment by Keruspe** [comment] 2020-02-23 14:42
Hmm, so everything is properly enqueued but something weird is going on indeed: 

- with amqp we write 49160 bytes at once, then process with the rest as expected
- with amqps we write 16384 bytes 3 times, which makes 49152 bytes total (so several bytes are missing to actually finish the payload itself).

Two things to investigate: what prevents us to send more than 16384 at once, and why aren't we trying to send the rest.

Can you reproduce if you disable defaults features and enable the rustls feature?

**Comment by hylobates-agilis** [comment] 2020-02-23 15:05
Not sure about it. Is this in `Cargo.toml`:
```
[features]
rustls = ["lapin/rustls"]
```
And building with:
```
cargo build --no-default-features --features=rustls
```

enough? Or should I do something else?

**Comment by hylobates-agilis** [comment] 2020-02-23 15:20
NVM, just figured it out:
```
[dependencies.lapin]
version = "0.28.4"
default-features = false
features = ["rustls"]
```
(sorry, not yet used to features)

Results:
* **without** `chan.close()` at the end, nothing is delivered
* **with** `chan.close()` at the end, message is delivered

Traces below.

[rustls_chan_close.txt](https://github.com/sozu-proxy/lapin/files/4241467/rustls_chan_close.txt)
[rustls_no_chan_close.txt](https://github.com/sozu-proxy/lapin/files/4241468/rustls_no_chan_close.txt)

**Comment by Keruspe** [comment] 2020-02-23 15:55
One last test: could you try with openssl feature instead of rustls ?

**Comment by hylobates-agilis** [comment] 2020-02-23 16:13
Unable to compile (8 errors total):
```
   Compiling tcp-stream v0.8.0
error[E0277]: `?` couldn't convert the error to `HandshakeError`
   --> /home/mortal/.cargo/registry/src/github.com-1ecc6299db9ec823/tcp-stream-0.8.0/src/lib.rs:216:79
    |
216 |                 let identity = openssl::pkcs12::Pkcs12::from_der(identity.der)?.parse(identity.password)?;
    |                                                                               ^ the trait `std::convert::From<openssl::error::ErrorStack>` is not implemented for `HandshakeError`
    |
    = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
    = help: the following implementations were found:
              <HandshakeError as std::convert::From<openssl::ssl::error::HandshakeError<mio::net::tcp::TcpStream>>>
              <HandshakeError as std::convert::From<std::io::Error>>
    = note: required by `std::convert::From::from`

error[E0277]: `?` couldn't convert the error to `HandshakeError`
   --> /home/mortal/.cargo/registry/src/github.com-1ecc6299db9ec823/tcp-stream-0.8.0/src/lib.rs:216:105
    |
216 |                 let identity = openssl::pkcs12::Pkcs12::from_der(identity.der)?.parse(identity.password)?;
    |                                                                                                         ^ the trait `std::convert::From<openssl::error::ErrorStack>` is not implemented for `HandshakeError`
    |
    = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
    = help: the following implementations were found:
              <HandshakeError as std::convert::From<openssl::ssl::error::HandshakeError<mio::net::tcp::TcpStream>>>
              <HandshakeError as std::convert::From<std::io::Error>>
    = note: required by `std::convert::From::from`

error[E0609]: no field `0` on type `openssl::pkcs12::ParsedPkcs12`
   --> /home/mortal/.cargo/registry/src/github.com-1ecc6299db9ec823/tcp-stream-0.8.0/src/lib.rs:217:50
    |
217 |                 builder.set_certificate(identity.0.cert)?;
    |                                                  ^ unknown field
    |
    = note: available fields are: `pkey`, `cert`, `chain`

error[E0277]: `?` couldn't convert the error to `HandshakeError`
   --> /home/mortal/.cargo/registry/src/github.com-1ecc6299db9ec823/tcp-stream-0.8.0/src/lib.rs:217:57
    |
217 |                 builder.set_certificate(identity.0.cert)?;
    |                                                         ^ the trait `std::convert::From<openssl::error::ErrorStack>` is not implemented for `HandshakeError`
    |
    = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
    = help: the following implementations were found:
              <HandshakeError as std::convert::From<openssl::ssl::error::HandshakeError<mio::net::tcp::TcpStream>>>
              <HandshakeError as std::convert::From<std::io::Error>>
    = note: required by `std::convert::From::from`

error[E0609]: no field `0` on type `openssl::pkcs12::ParsedPkcs12`
   --> /home/mortal/.cargo/registry/src/github.com-1ecc6299db9ec823/tcp-stream-0.8.0/src/lib.rs:218:50
    |
218 |                 builder.set_private_key(identity.0.pkey)?;
    |                                                  ^ unknown field
    |
    = note: available fields are: `pkey`, `cert`, `chain`

error[E0277]: `?` couldn't convert the error to `HandshakeError`
   --> /home/mortal/.cargo/registry/src/github.com-1ecc6299db9ec823/tcp-stream-0.8.0/src/lib.rs:218:57
    |
218 |                 builder.set_private_key(identity.0.pkey)?;
    |                                                         ^ the trait `std::convert::From<openssl::error::ErrorStack>` is not implemented for `HandshakeError`
    |
    = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
    = help: the following implementations were found:
              <HandshakeError as std::convert::From<openssl::ssl::error::HandshakeError<mio::net::tcp::TcpStream>>>
              <HandshakeError as std::convert::From<std::io::Error>>
    = note: required by `std::convert::From::from`

error[E0609]: no field `0` on type `openssl::pkcs12::ParsedPkcs12`
   --> /home/mortal/.cargo/registry/src/github.com-1ecc6299db9ec823/tcp-stream-0.8.0/src/lib.rs:219:51
    |
219 |                 if let Some(ref chain) = identity.0.chain {
    |                                                   ^ unknown field
    |
    = note: available fields are: `pkey`, `cert`, `chain`

error[E0277]: `?` couldn't convert the error to `HandshakeError`
   --> /home/mortal/.cargo/registry/src/github.com-1ecc6299db9ec823/tcp-stream-0.8.0/src/lib.rs:221:70
    |
221 |                         builder.add_extra_chain_cert(cert.to_owned())?;
    |                                                                      ^ the trait `std::convert::From<openssl::error::ErrorStack>` is not implemented for `HandshakeError`
    |
    = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
    = help: the following implementations were found:
              <HandshakeError as std::convert::From<openssl::ssl::error::HandshakeError<mio::net::tcp::TcpStream>>>
              <HandshakeError as std::convert::From<std::io::Error>>
    = note: required by `std::convert::From::from`

error: aborting due to 8 previous errors
```

Maybe I’m missing something?

**Comment by Keruspe** [comment] 2020-02-23 16:16
Huh, that's weird, I’ll fix this part and get back to you!
Thanks for the help!

**Comment by hylobates-agilis** [comment] 2020-02-23 18:38
I now have some kind of workaround (using rustls) for what I'm currently doing, so thank you :)

**Comment by Keruspe** [comment] 2020-02-24 09:01
If you run `cargo update` to update `tcp-stream` you should now be able to test with openssl

**Comment by hylobates-agilis** [comment] 2020-02-24 13:45
Yep, seems fixed, I was able to compile everything with openssl features. Here are the results:
* **without chan close**, message is not delivered
* **with chan close*, message is not delivered and `chan.close()` call hangs indefinitely

[openssl_chan_close.txt](https://github.com/sozu-proxy/lapin/files/4244828/openssl_chan_close.txt)
[openssl_no_chan_close.txt](https://github.com/sozu-proxy/lapin/files/4244829/openssl_no_chan_close.txt)

So the only workaround for now is to use `rustls` and close the channel or tx_commit.

**Comment by Keruspe** [comment] 2020-02-24 14:25
Wrt the channel_close VS no channel_close thing: it's actually normal.

basic_publish doesn't expect any response from the AMQP server, so it's considered as "completed" once everything has been queued in the socket. If the program exits too fast after that, the message may never have been sent, there's no way to tell. Calling a method like channel_close which expects a reply will cause us to wait for a reply (the body from the basic_publish will have been fully sent at this point).

The other alternative it to call confirm_select after creating the channel, which enables the publisher_confirms extension on this channel, and then to call wait_for_confirms to wait for the AMQP server to confirm the reception of the published messages.

**Comment by Keruspe** [comment] 2020-02-24 14:27
Wrt the TLS implementations:

native-tls uses openssl under the hood on linux, testing with openssl just confirmed that the problem is inside of the openssl interactions, and not in the thin native-tls layer above.
rustls is a whole other stack, which is promising but not yet feature-complete wrt lapin (no support for pcks11 identity yet), that's why it's not the default.

I'll dig into openssl to try and find out what's going on.

**Comment by Keruspe** [comment] 2020-02-24 14:48
Can you retry with 0.29.1 to confirm it's properly fixed now?

**Closed by Keruspe** 2020-02-24 14:48 UTC

**Comment by hylobates-agilis** [comment] 2020-02-24 17:35
Works perfectly!! Thanks very much for the time, support and complementary explanation, really appreciated!
