### ISSUE TITLE
Connection hangs on SSL certificate error

### ISSUE THREAD

**Issue by ajnewlands** [sozu-proxy/lapin#237] opened 2020-03-02 23:02 UTC
When attempting to connect to a rabbitmq server with an untrusted server certificate (i.e. because a CA cert has yet to be imported) lapin will hang. This can be tested by setting rabbitmq up with a self-signed certificate and adding/removing the CA cert to demonstrate that it does connect when the servers identity can be verified but hangs when it is not (instead of returning an error indicating that the servers identity cannot be established).

log output with RUST_LOG="trace" set;

     Running `target/debug/lapin_test`
[2020-03-02T22:53:54Z TRACE mio::poll] registering with poller
^C

sample code to reproduce:

    env_logger::init();
    match Connection::connect("amqps://user:secret@my.rabbit.host:5671/%2f", ConnectionProperties::default()).wait() {
        Ok(_conn) => println!("Connected"),
        Err(e) => println!("Connection failed: {:?}", e) ,
   };

**Comment by ajnewlands** [comment] 2020-03-02 23:40
I should note that this was observed on Linux.

**Comment by Keruspe** [comment] 2020-03-03 12:23
Thanks for the report, will look into it

**Comment by jbg** [comment] 2020-03-04 05:52
Also hit this on Linux, seems that a recent update switched the rustls connector to using native-certs by default, and because we deploy static binaries to bare metal it no longer had any CA certs. Didn't get any error, just hanging on trying to open the connection.

**Comment by Keruspe** [comment] 2020-03-04 08:56
Nah, it's only true for 0.33.0-beta.1 and native-tls is still the default, not rustls.

I can reproduce, though, so i'll be able to track this down

**Comment by jbg** [comment] 2020-03-04 09:26
Sorry if I wasn't clear. We disable default features and enable the `rustls` feature, and always have. Previously this used compiled-in certificates (webpki-roots) and now it appears to look for CA certificates in the filesystem, which triggered this bug until we realised what was going on.

I noticed there is a new feature `rustls-webpki-roots-certs` which looks like it should do what we want, but the "default when rustls is used" does seem to have changed.

Minor nit: Features are supposed to be purely additive. You have two features as alternatives (`rustls-native-certs` and `rustls-webpki-roots-certs`) which is fine, but neither of them should be pulled in by `rustls` because it's impossible to disable a feature selectively, so enabling `rustls` and `rustls-webpki-roots-certs` results in all three being enabled.

Sorry for the slight thread drift.

**Comment by Keruspe** [comment] 2020-03-04 09:33
The `rustls` feature is there only to pick a default rustls behaviour. If you use rustls, you use what lapin sets as the default, and if you want to pin to a specific behaviour you can either use rustls-native-certs or rustls-webpki-roots-certs. The rustls feature does nothing more than pick one of those two.

This *definitely* should be documented. If you're willing to, contributions in this area are really appreciated!

As for the bug, if you run cargo update to pull in amq-protocol 4.2.2 it should be fixed now!

**Closed by Keruspe** 2020-03-04 09:33 UTC
