### ISSUE TITLE
 cannot be formatted with the default formatter v0.33.1

### ISSUE THREAD

**Issue by aliaksandr-master** [sozu-proxy/lapin#240] opened 2020-03-23 10:58 UTC
I have installed new version of lapin (0.33.1)

`cargo 1.42.0 (86334295e 2020-01-31)`
`rustup 1.21.1 (7832b2ebe 2019-12-20)`
`rustc 1.42.0 (b8cedc004 2020-03-09)`

![Screenshot from 2020-03-23 13-54-38](https://user-images.githubusercontent.com/3963029/77309554-e90a7300-6d0d-11ea-8b53-568401537c50.png)

**Comment by Keruspe** [comment] 2020-03-23 11:00
Huh? Could you paste your Cargo.toml + Cargo.lock so that I can reproduce?

**Comment by Keruspe** [comment] 2020-03-23 11:18
ok, should be fixed in 0.33.2, was caused by nom having its default features disabled and us needing the std feature without declaring it

**Closed by Keruspe** 2020-03-23 11:18 UTC
