### ISSUE TITLE
Basic Get with Asnyc/Await or wait using the new PinkySwear

### ISSUE THREAD

**Issue by asevans48** [sozu-proxy/lapin#235] opened 2020-02-25 07:18 UTC
**Overview**
In attempting to use basic get with version 0.29.1, the call gets stuck waiting for the _BasicGetMessage_. Please provide a working example or provide guidance on a solution.

Thanks and keep up the good work.

**Expectation**
Basic Get succeeds when presented with an appropriate AMQP url that works in the consumer.

**Result**
The _basic_get_ function gets stuck waiting for a result

**Technology**

Windows 10
Rust Stable latest
amqp_protocol and amqp_protocol_types 4.0.0
lapin 0.29.1

**Code**

```
let bopts = BasicGetOptions::default();
println!("Attempting Get {}", qname.clone());
println!("{}", channel.status().is_connected());
let pinky_swear = channel.basic_get(&qname, bopts);
println!("Awaiting Get");
let nc = pinky_swear.wait(); 
//let nc = pinky_swear.await;
println!("Received Message");
```

**Output**
```
Attempting Get lapin_test_queue
true
Awaiting Get
```

**Comment by Keruspe** [comment] 2020-02-25 07:24
Hi,

Can you run this with `RUST_LOG=trace` please (you will need to call `env_logger::init()`)?

Any chance you can try the same code on a linux box? I suspect this may be a windows-specific issue as I cannot reproduce here

**Comment by asevans48** [comment] 2020-02-25 18:34
Here is the section pertaining to the function calls. The channels return and are usable. The basic setup contains a few hundred lines but there was nothing wrong:

```
[2020-02-25T18:26:55Z TRACE lapin::connection] will handle frame: Method(2, Queue(BindOk(BindOk)))
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop send continue; can_read=true, can_write=true, has_data=false
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop do_run done; can_read=true, can_write=true, has_data=false, status=Setup
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop run
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop poll
[2020-02-25T18:26:55Z TRACE mio::sys::windows::selector] select; timeout=Some(0ns)
[2020-02-25T18:26:55Z TRACE mio::sys::windows::selector] polling IOCP
[2020-02-25T18:26:55Z TRACE mio::sys::windows::selector] returning
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop poll done
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop do_run; can_read=true, can_write=true, has_data=false
[2020-02-25T18:26:55Z TRACE mio::sys::windows::selector] set readiness to Writable
[2020-02-25T18:26:55Z TRACE mio::sys::windows::tcp] scheduling a read
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop do_run done; can_read=false, can_write=true, has_data=false, status=Setup
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop run
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop poll
[2020-02-25T18:26:55Z TRACE mio::sys::windows::selector] select; timeout=Some(0ns)
[2020-02-25T18:26:55Z TRACE mio::sys::windows::selector] polling IOCP
[2020-02-25T18:26:55Z TRACE mio::sys::windows::selector] returning
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop poll done
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop do_run; can_read=false, can_write=true, has_data=false
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop do_run done; can_read=false, can_write=true, has_data=false, status=Setup
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop run
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop poll
[2020-02-25T18:26:55Z TRACE mio::sys::windows::selector] select; timeout=Some(60s)
[2020-02-25T18:26:55Z TRACE mio::sys::windows::selector] polling IOCP
Attempting Get lapin_test_queue
true
[2020-02-25T18:26:55Z TRACE lapin::connection] connection send_frame; channel_id=2
[2020-02-25T18:26:55Z TRACE lapin::frames] channel 2 state is now waiting for ExpectedReply(BasicGetOk(Pinky, ShortString("lapin_test_queue")))
[2020-02-25T18:26:55Z TRACE lapin::connection] connection set readable
Awaiting Get
[2020-02-25T18:26:55Z TRACE mio::sys::windows::selector] returning
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop poll done
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop do_run; can_read=false, can_write=true, has_data=true
[2020-02-25T18:26:55Z TRACE lapin::io_loop] will write to buffer: Method(2, Basic(Get(Get { queue: ShortString("lapin_test_queue"), no_ack: false })))
[2020-02-25T18:26:55Z TRACE mio::sys::windows::selector] set readiness to (empty)
[2020-02-25T18:26:55Z TRACE mio::sys::windows::tcp] scheduling a write of 32 bytes
[2020-02-25T18:26:55Z TRACE mio::sys::windows::tcp] done immediately with 32 bytes
[2020-02-25T18:26:55Z TRACE mio::sys::windows::selector] set readiness to Writable
[2020-02-25T18:26:55Z TRACE lapin::io_loop] wrote 32 bytes
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop send continue; can_read=false, can_write=true, has_data=true
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop do_run done; can_read=false, can_write=true, has_data=true, status=Setup
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop run
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop poll
[2020-02-25T18:26:55Z TRACE mio::sys::windows::selector] select; timeout=Some(0ns)
[2020-02-25T18:26:55Z TRACE mio::sys::windows::selector] polling IOCP
[2020-02-25T18:26:55Z TRACE mio::sys::windows::selector] returning
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop poll done
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop do_run; can_read=false, can_write=true, has_data=true
[2020-02-25T18:26:55Z TRACE lapin::io_loop] wrote 0 bytes
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop do_run done; can_read=false, can_write=true, has_data=false, status=Setup
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop run
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop poll
[2020-02-25T18:26:55Z TRACE mio::sys::windows::selector] select; timeout=Some(60s)
[2020-02-25T18:26:55Z TRACE mio::sys::windows::selector] polling IOCP
[2020-02-25T18:26:55Z TRACE mio::sys::windows::selector] select; -> got overlapped
[2020-02-25T18:26:55Z TRACE mio::sys::windows::tcp] finished a read: 0
[2020-02-25T18:26:55Z TRACE mio::sys::windows::selector] set readiness to Readable | Writable
[2020-02-25T18:26:55Z TRACE mio::sys::windows::selector] returning
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop poll done
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop do_run; can_read=true, can_write=true, has_data=false
[2020-02-25T18:26:55Z TRACE lapin::io_loop] read 549 bytes
[2020-02-25T18:26:55Z TRACE lapin::connection] will handle frame: Method(2, Basic(GetOk(GetOk { delivery_tag: 1, redelivered: true, exchange: ShortString("test_exchange"), routing_key: ShortString("test_key"), message_count: 138331 })))
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop send continue; can_read=true, can_write=true, has_data=false
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop do_run done; can_read=true, can_write=true, has_data=false, status=Setup
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop run
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop poll
[2020-02-25T18:26:55Z TRACE mio::sys::windows::selector] select; timeout=Some(0ns)
[2020-02-25T18:26:55Z TRACE mio::sys::windows::selector] polling IOCP
[2020-02-25T18:26:55Z TRACE mio::sys::windows::selector] returning
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop poll done
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop do_run; can_read=true, can_write=true, has_data=false
[2020-02-25T18:26:55Z TRACE mio::sys::windows::selector] set readiness to Writable
[2020-02-25T18:26:55Z TRACE mio::sys::windows::tcp] scheduling a read
[2020-02-25T18:26:55Z TRACE lapin::connection] will handle frame: Header(2, 60, AMQPContentHeader { class_id: 60, weight: 0, body_size: 60, properties: AMQPProperties { content_type: Some(ShortString("application/json")), content_encoding: Some(ShortString("utf-8")), headers: Some(FieldTable({ShortString("eta"): Timestamp(10000), ShortString("expires"): Timestamp(36000000), ShortString("group"): Void, ShortString("id"): LongString(LongString("fafcc636-68f3-40d8-86c4-72f9228a755e")), ShortString("lang"): LongString(LongString("rs")), ShortString("origin"): LongString(LongString("gen9800@ZBOX-V31IVG2581")), ShortString("parent_id"): Void, ShortString("retries"): ShortShortInt(0), ShortString("root_id"): LongString(LongString("80842bc8-b5be-4513-a8c8-2ba01f12bd9f")), ShortString("shadow"): LongString(LongString("test_task")), ShortString("task"): LongString(LongString("test_task")), ShortString("timelimit"): FieldArray(FieldArray([Timestamp(36000000), Timestamp(36000000)]))})), delivery_mode: Some(2), priority: Some(0), correlation_id: Some(ShortString("fafcc636-68f3-40d8-86c4-72f9228a755e")), reply_to: Some(ShortString("e20bb204-d2ee-48a8-beb2-1e4d874c6546")), expiration: None, message_id: Some(ShortString("cffe6894-7774-4be0-8de1-965e204f1b5e")), timestamp: None, kind: None, user_id: None, app_id: None, cluster_id: None } })
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop send continue; can_read=false, can_write=true, has_data=false
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop do_run done; can_read=false, can_write=true, has_data=false, status=Setup
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop run
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop poll
[2020-02-25T18:26:55Z TRACE mio::sys::windows::selector] select; timeout=Some(0ns)
[2020-02-25T18:26:55Z TRACE mio::sys::windows::selector] polling IOCP
[2020-02-25T18:26:55Z TRACE mio::sys::windows::selector] returning
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop poll done
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop do_run; can_read=false, can_write=true, has_data=false
[2020-02-25T18:26:55Z TRACE lapin::connection] will handle frame: Body(2, [91, 91, 93, 44, 123, 125, 44, 123, 34, 99, 97, 108, 108, 98, 97, 99, 107, 115, 34, 58, 91, 93, 44, 34, 99, 104, 97, 105, 110, 34, 58, 91, 93, 44, 34, 99, 104, 111, 114, 100, 34, 58, 91, 93, 44, 34, 101, 114, 114, 98, 97, 99, 107, 115, 34, 58, 91, 93, 125, 93])
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop do_run done; can_read=false, can_write=true, has_data=false, status=Setup
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop run
[2020-02-25T18:26:55Z TRACE lapin::io_loop] io_loop poll
[2020-02-25T18:26:55Z TRACE mio::sys::windows::selector] select; timeout=Some(60s)
[2020-02-25T18:26:55Z TRACE mio::sys::windows::selector] polling IOCP
[2020-02-25T18:27:24Z TRACE mio::sys::windows::selector] select; -> got overlapped
[2020-02-25T18:27:24Z TRACE mio::sys::windows::tcp] finished a read: 0
[2020-02-25T18:27:24Z TRACE mio::sys::windows::selector] set readiness to Readable | Writable
[2020-02-25T18:27:24Z TRACE mio::sys::windows::selector] returning
[2020-02-25T18:27:24Z TRACE lapin::io_loop] io_loop poll done
[2020-02-25T18:27:24Z TRACE lapin::io_loop] io_loop do_run; can_read=true, can_write=true, has_data=false
[2020-02-25T18:27:24Z TRACE lapin::io_loop] read 8 bytes
[2020-02-25T18:27:24Z TRACE lapin::connection] will handle frame: Heartbeat(0)
[2020-02-25T18:27:24Z DEBUG lapin::connection] received heartbeat from server
[2020-02-25T18:27:24Z TRACE lapin::io_loop] io_loop send continue; can_read=true, can_write=true, has_data=false
[2020-02-25T18:27:24Z TRACE lapin::io_loop] io_loop do_run done; can_read=true, can_write=true, has_data=false, status=Setup
[2020-02-25T18:27:24Z TRACE lapin::io_loop] io_loop run
[2020-02-25T18:27:24Z TRACE lapin::io_loop] io_loop poll
[2020-02-25T18:27:24Z TRACE mio::sys::windows::selector] select; timeout=Some(0ns)
[2020-02-25T18:27:24Z TRACE mio::sys::windows::selector] polling IOCP
[2020-02-25T18:27:24Z TRACE mio::sys::windows::selector] returning
[2020-02-25T18:27:24Z TRACE lapin::io_loop] io_loop poll done
[2020-02-25T18:27:24Z TRACE lapin::io_loop] io_loop do_run; can_read=true, can_write=true, has_data=false
[2020-02-25T18:27:24Z TRACE mio::sys::windows::selector] set readiness to Writable
[2020-02-25T18:27:24Z TRACE mio::sys::windows::tcp] scheduling a read
[2020-02-25T18:27:24Z TRACE lapin::io_loop] io_loop do_run done; can_read=false, can_write=true, has_data=false, status=Setup
[2020-02-25T18:27:24Z TRACE lapin::io_loop] io_loop run
[2020-02-25T18:27:24Z TRACE lapin::io_loop] io_loop poll
[2020-02-25T18:27:24Z TRACE mio::sys::windows::selector] select; timeout=Some(0ns)
[2020-02-25T18:27:24Z TRACE mio::sys::windows::selector] polling IOCP
[2020-02-25T18:27:24Z TRACE mio::sys::windows::selector] returning
```

**Comment by asevans48** [comment] 2020-02-25 18:36
It appears to receive the message:

```
[2020-02-25T18:26:55Z TRACE lapin::connection] will handle frame: Header(2, 60, AMQPContentHeader { class_id: 60, weight: 0, body_size: 60, properties: AMQPProperties { content_type: Some(ShortString("application/json")), content_encoding: Some(ShortString("utf-8")), headers: Some(FieldTable({ShortString("eta"): Timestamp(10000), ShortString("expires"): Timestamp(36000000), ShortString("group"): Void, ShortString("id"): LongString(LongString("fafcc636-68f3-40d8-86c4-72f9228a755e")), ShortString("lang"): LongString(LongString("rs")), ShortString("origin"): LongString(LongString("gen9800@ZBOX-V31IVG2581")), ShortString("parent_id"): Void, ShortString("retries"): ShortShortInt(0), ShortString("root_id"): LongString(LongString("80842bc8-b5be-4513-a8c8-2ba01f12bd9f")), ShortString("shadow"): LongString(LongString("test_task")), ShortString("task"): LongString(LongString("test_task")), ShortString("timelimit"): FieldArray(FieldArray([Timestamp(36000000), Timestamp(36000000)]))})), delivery_mode: Some(2), priority: Some(0), correlation_id: Some(ShortString("fafcc636-68f3-40d8-86c4-72f9228a755e")), reply_to: Some(ShortString("e20bb204-d2ee-48a8-beb2-1e4d874c6546")), expiration: None, message_id: Some(ShortString("cffe6894-7774-4be0-8de1-965e204f1b5e")), timestamp: None, kind: None, user_id: None, app_id: None, cluster_id: None } })
```

**Comment by Keruspe** [comment] 2020-02-25 18:47
I have fixed a bug in 0.31.0 wrt basic_get amongst other things, if the queue wasn’t declared in the channel issuing the basic get.
Could you give this a try?

**Comment by asevans48** [comment] 2020-02-25 18:53
so I will need to run queue declare before running the basic get? Would it be better if basic_get worked like a consumer and took the queue reference? Anyway, trying now. Thanks for the quick reply.

**Comment by asevans48** [comment] 2020-02-25 18:57
it worked

**Comment by Keruspe** [comment] 2020-02-25 18:57
Well, with 0.31.0 this requirement is gone, it was due to a bug inside lapin. Basic_consume also takes an &str now that the bug has been identified and fixed

**Comment by Keruspe** [comment] 2020-02-25 19:10
Thanks for confirming that it works now !

Closing this issue

**Closed by Keruspe** 2020-02-25 19:10 UTC
