### ISSUE TITLE
Issues testing due to reused connections

### ISSUE THREAD

**Issue by SillyMoo** [sozu-proxy/lapin#275] opened 2020-05-03 13:41 UTC
When running tests that each create and close a connection to the same server I am getting errors when running without a parallelism of 1. It looks like under the covers the same connection is shared, so that if test thread 1 creates a connection to AMQP server 1, and test thread 2 creates a connection to AMQP server 1 under the covers it is the same connection. So then test thread 1 closes the connection and test thread 2 errors whilst trying to use it.
(FYI, this is when using async_std to run the tests async)

**Comment by Keruspe** [comment] 2020-05-03 13:43
That sounds odd, could you provide a minimal example to reproduce the issue?

**Comment by SillyMoo** [comment] 2020-05-03 14:09
Sure, see attached. Probably something daft I've done (I'm still a rust neophyte), if I run with `cargo test` it fails if I run with `cargo test -- --test-threads=1` it passes. Running either test individually also passes.
[test_repo.zip](https://github.com/sozu-proxy/lapin/files/4570613/test_repo.zip)

(Note, as it's a race condition you may have to run it a couple of times before it fails)

**Comment by Keruspe** [comment] 2020-05-03 19:19
Will give it a try!

**Comment by Keruspe** [comment] 2020-05-03 21:49
Ok, the issue is not due to the tests running in parallel affecting each other. It's easier to reproduce it this way as there is more activity in the rabbitmq server but that's all.

We need to split ChannelState and ChannelReceivingState or something like this, the like we Split ConnectionStep out of ConnectionState.
The problem here is that we hit this sequence:
- send close + mark as closing
- receive contents for consumer
- receive close-ok

Since we're in the Closing state and not in the ReceivingContent one, we bail out

**Comment by Keruspe** [comment] 2020-05-03 22:19
I have two fixes locally, will push those tomorrow

**Comment by SillyMoo** [comment] 2020-05-04 07:15
That's great. Feel free to steal my code for a test if you like (even if it was fluke that it reproduced the issue).

**Comment by Keruspe** [comment] 2020-05-04 08:30
I have some cleanup of this part in progress locally, but current master shouldn't have the problem anymore. Will make another beta release soonish

**Closed by Keruspe** 2020-05-04 08:30 UTC

**Comment by SillyMoo** [comment] 2020-05-04 09:22
Sweet, thanks for pushing this through so quickly.
