### ISSUE TITLE
Cannot connect to AMQP server in 0.33.0 version.

### ISSUE THREAD

**Issue by frondeus** [sozu-proxy/lapin#239] opened 2020-03-18 09:47 UTC
I can connect in 0.32.0.
Using async await. 

Program is waiting forever for a connection, the server is never receiving connection request.

**Comment by Keruspe** [comment] 2020-03-18 09:49
Could you provide logs with `RUST_LOG=trace`?

**Comment by Keruspe** [comment] 2020-03-18 09:54
Also, which operating system are you using?

**Comment by frondeus** [comment] 2020-03-18 10:06
Client system - MacOS 10.15.3 Catalina
Rust version - nightly-2019-10-31 (unfortunately cannot upgrade it now)
Server system - docker image `rabbitmq:3.7.17-management`

Logs:
https://gist.github.com/frondeus/2632e36add2a2e76f86570df257588e4

**Comment by Keruspe** [comment] 2020-03-18 10:21
Ok, two "problems" here:

First one might not be too bad: socket tells us it's readable, but when we try and read on it, we only read 0 and don't hit wouldblock.

Second one, and this is our problem here: we have two mio wakers, one in the Connection to tell that there is some data to write, one other in the IoLoop to tell poll we still have business to do.
In the current case, both are firing, and it seems that poll only receives one event.

Since it works fine on both linux and windows, I'm pretty sure it's macos specific.

Will try and dig in this direction to try and submit a useful bug report wrt that in mio 0.7.

**Comment by Keruspe** [comment] 2020-03-18 10:38
Let's see what mio's CI has to say about this: https://github.com/tokio-rs/mio/pull/1283

**Comment by Keruspe** [comment] 2020-03-18 10:47
mio's CI confirmed my suspicion, there's a bug using multiple wakers which only affects macos and ios.

Will try and update this part to do this in a different manner if it cannot be fixed in mio 0.7

**Comment by Keruspe** [comment] 2020-03-18 11:10
Should be fixed in 0.33.1

**Closed by Keruspe** 2020-03-18 11:10 UTC

**Comment by frondeus** [comment] 2020-03-18 11:15
Can confirm. Everything works :)
